### PR TITLE
Migrate from React.PropTypes to prop-types

### PR DESCRIPTION
**Pull request by altwohill**
React 16 no-longer provides PropTypes. Should use `prop-types` module instead

### CODE REVIEW

**Comment by lexor90** [comment]
Hello there @mobiusnz 
thank you very much for this PR and sorry about the delay I'm replying with.

I'm going to check it and get back to you shortly.

**Comment by indrajaumil** [comment]
Hi @lexor90 can you please let us know when this fix can be release?

**Comment by lexor90** [comment]
Hey there @khancute and @mobiusnz sorry about the delay.
It took me a while to create an app to test changes, by the way it looks good to me.

I was specifically wanting to test the style changes on the Android platform  because the font size has been increased by 1 (34/2 => 17, not 18), so I wanted to make sure it was properly working, by the way it does.

I'm going to accept this and push a new version right now.

**Comment by lexor90** [comment]
Published on npm `react-native-credit-card-input-fullpage@0.2.0`

Thank you @mobiusnz

**Comment by indrajaumil** [comment]
@lexor90 Thank you. Cheers

**Pull request merged**
